[project]
name = "formtool"
version = "0.1.0"
description = "ffmpeg command shortcuts"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "hypy-utils>=1.0.29",
]

[project.scripts]
formtool = "formtool.__main__:cli"
